#
db_name: wordpress
#
db_user: wordpress
#
db_user_password: P@ssw0rd
#
db_host: localhost
#
root_password: P@ssw0rd
root_login: root
#
#
start_db: mariadb
start_web: httpd
#Web configure
web_path: /var/www/html
web_owner: apache
web_group: apache
#
wordpress_file_path: /wordpress/wp-config.php
wordpress_file_default: /wordpress/wp-config-sample.php
