apiVersion: v1
kind: ServiceAccount
metadata:
  name: diagnostic-tools
  namespace: dev

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader
  namespace: dev
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods
  namespace: dev
subjects:
- kind: ServiceAccount
  name: diagnostic-tools
  namespace: dev
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: diagnostic-tools
  namespace: dev
spec:
  selector:
    matchLabels:
      app: diagnostic-tools
  template:
    metadata:
      labels:
        app: diagnostic-tools
    spec:
      serviceAccountName: diagnostic-tools
      containers:
      - name: diagnostic-container
        image: bitnami/kubectl
        command: ["sh", "-c", "echo 'WordPress Pods:' && kubectl get pods -n dev -l app=wordpress"]