pipeline {
    agent {
        docker {
            image 'maven:3.9.0'
            args '-v /root/.m2:/root/.m2'
        }
    }

    environment {
        GITHUB_CRED = "github-ssh"
        GITHUB_URL = "https://github.com/pasqueque/codeby-devops"
        APPS = ['lesson26/devops-app', 'lesson26/jenkins-app', 'lesson26/world-app']
    }

    stages {
        stage('Check out') {
            steps {
                git branch: 'lesson26', changelog: false, credentialsId: env.GITHUB_CRED, poll: false, url: env.GITHUB_URL
            }
        }

        stage('Build and Test') {
            parallel {
                for (appDir in env.APPS) {
                    stage("${appDir}") {
                        steps {
                            dir(appDir) {
                                script {
                                    sh 'mvn -B -DskipTests clean package'
                                    sh 'mvn test'
                                }
                            }
                        }
                        post {
                            always {
                                junit("${appDir}/target/surefire-reports/*.xml")
                            }
                        }
                    }
                }
            }
        }
    }
}
