pipeline {
    agent {
        docker {
            image 'maven:3.9.0'
            args '-v /root/.m2:/root/.m2'
        }
    }

    environment {
        GITHUB_CRED = "github-ssh"
        GITHUB_URL = "https://github.com/pasqueque/codeby-devops"
        APP_DEVOPS = "lesson26/devops-app"
        APP_JENKINS = "lesson26/jenkins-app"
        APP_WORLD = "lesson26/world-app"
    }

    stages {
        stage('Check out') {
            steps {
                git branch: 'lesson26', changelog: false, credentialsId: env.GITHUB_CRED, poll: false, url: env.GITHUB_URL
            }
        }

        stage('Build and Test') {
            parallel {
                stage("${env.APP_DEVOPS}") {
                    steps {
                        dir(env.APP_DEVOPS) {
                            script {
                                sh 'mvn -B -DskipTests clean package'
                                sh 'mvn test'
                            }
                        }
                    }
                    post {
                        always {
                            junit("${env.APP_DEVOPS}/target/surefire-reports/*.xml")
                        }
                    }
                }

                stage("${env.APP_JENKINS}") {
                    steps {
                        dir(env.APP_JENKINS) {
                            script {
                                sh 'mvn -B -DskipTests clean package'
                                sh 'mvn test'
                            }
                        }
                    }
                    post {
                        always {
                            junit("${env.APP_JENKINS}/target/surefire-reports/*.xml")
                        }
                    }
                }

                stage("${env.APP_WORLD}") {
                    steps {
                        dir(env.APP_WORLD) {
                            script {
                                sh 'mvn -B -DskipTests clean package'
                                sh 'mvn test'
                            }
                        }
                    }
                    post {
                        always {
                            junit("${env.APP_WORLD}/target/surefire-reports/*.xml")
                        }
                    }
                }

            }
        }
    }
}
